//---------------------------------------------------------------------------
#ifndef MainH
#define MainH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <Menus.hpp>
//---------------------------------------------------------------------------
class TForm1 : public TForm
{
__published:	// IDE-managed Components
    TMainMenu *MainMenu;
    TMenuItem *N1;
    TMenuItem *MenuItem1;
    TMenuItem *Open1;
    TMenuItem *Save1;
    TMenuItem *SaveAs1;
    TMenuItem *N8;
    TMenuItem *Properties1;
    TMenuItem *CloseAll1;
    TMenuItem *List1;
    TMenuItem *N7;
    TMenuItem *Importfrom1;
    TMenuItem *AutoCADDXF1;
    TMenuItem *Exportto1;
    TMenuItem *AutoCADDXF2;
    TMenuItem *HPGL1;
    TMenuItem *RasterImage1;
    TMenuItem *N4;
    TMenuItem *Print1;
    TMenuItem *N2;
    TMenuItem *Exit1;
    TMenuItem *Edit1;
    TMenuItem *Undo2;
    TMenuItem *Redo2;
    TMenuItem *N9;
    TMenuItem *Cut1;
    TMenuItem *Copy2;
    TMenuItem *Paste1;
    TMenuItem *N10;
    TMenuItem *ObjectsProperties1;
    TMenuItem *N3;
    TMenuItem *Copy1;
    TMenuItem *Move1;
    TMenuItem *Rotate1;
    TMenuItem *Scale1;
    TMenuItem *Mirror1;
    TMenuItem *Explode1;
    TMenuItem *N6;
    TMenuItem *Group1;
    TMenuItem *N11;
    TMenuItem *Erase1;
    TMenuItem *View1;
    TMenuItem *ZoomAll1;
    TMenuItem *ZoomWindow1;
    TMenuItem *ZoomPage2;
    TMenuItem *ZoomIn1;
    TMenuItem *ZoomOut1;
    TMenuItem *N5;
    TMenuItem *PageFirst1;
    TMenuItem *PageLasttEnd1;
    TMenuItem *PageNext1;
    TMenuItem *PagePrevious1;
    TMenuItem *N12;
    TMenuItem *SelectPage1;
    TMenuItem *N13;
    TMenuItem *SavecurrentView1;
    TMenuItem *ViewsList1;
    TMenuItem *Format1;
    TMenuItem *Page1;
    TMenuItem *Layer1;
    TMenuItem *Linetype1;
    TMenuItem *TextStyle1;
    TMenuItem *PointStyle1;
    TMenuItem *HatchStyle1;
    TMenuItem *Blocks1;
    TMenuItem *N14;
    TMenuItem *DimensionStyle1;
    TMenuItem *N15;
    TMenuItem *Grid1;
    TMenuItem *ObjectSnap1;
    TMenuItem *AngleSnap1;
    TMenuItem *N16;
    TMenuItem *Units1;
    TMenuItem *Private1;
    TMenuItem *Preferences1;
    TMenuItem *Draw1;
    TMenuItem *Point1;
    TMenuItem *Line1;
    TMenuItem *Polyline1;
    TMenuItem *Spline1;
    TMenuItem *Circle1;
    TMenuItem *centerradius1;
    TMenuItem *CenterDiameter1;
    TMenuItem *N2Points1;
    TMenuItem *N3point1;
    TMenuItem *Arc1;
    TMenuItem *ArcCSE;
    TMenuItem *ArcSEM;
    TMenuItem *ArcSME;
    TMenuItem *Ellipse1;
    TMenuItem *Rectangle1;
    TMenuItem *Dimension1;
    TMenuItem *Horizontal1;
    TMenuItem *Vertical1;
    TMenuItem *Parallel1;
    TMenuItem *Angular1;
    TMenuItem *Radius1;
    TMenuItem *Diameter1;
    TMenuItem *Ordinate1;
    TMenuItem *Hatch1;
    TMenuItem *N17;
    TMenuItem *Text1;
    TMenuItem *Symbol1;
    TMenuItem *InsertBlock1;
    TMenuItem *InsertImage1;
    TMenuItem *Tools1;
    TMenuItem *DistanceArea1;
    TMenuItem *PrintRectangles1;
    TMenuItem *Statistics1;
    TMenuItem *Help1;
    TMenuItem *About1;
    void __fastcall FormCreate(TObject *Sender);
    void __fastcall FormResize(TObject *Sender);
    void __fastcall FormDestroy(TObject *Sender);
    void __fastcall MenuItem1Click(TObject *Sender);
    void __fastcall Open1Click(TObject *Sender);
    void __fastcall Save1Click(TObject *Sender);
    void __fastcall SaveAs1Click(TObject *Sender);
    void __fastcall Properties1Click(TObject *Sender);
    void __fastcall CloseAll1Click(TObject *Sender);
    void __fastcall List1Click(TObject *Sender);
    void __fastcall AutoCADDXF1Click(TObject *Sender);
    void __fastcall AutoCADDXF2Click(TObject *Sender);
    void __fastcall HPGL1Click(TObject *Sender);
    void __fastcall RasterImage1Click(TObject *Sender);
    void __fastcall Print1Click(TObject *Sender);
    void __fastcall Exit1Click(TObject *Sender);
    void __fastcall Undo2Click(TObject *Sender);
    void __fastcall Redo2Click(TObject *Sender);
    void __fastcall Cut1Click(TObject *Sender);
    void __fastcall Copy2Click(TObject *Sender);
    void __fastcall Paste1Click(TObject *Sender);
    void __fastcall ObjectsProperties1Click(TObject *Sender);
    void __fastcall Copy1Click(TObject *Sender);
    void __fastcall Move1Click(TObject *Sender);
    void __fastcall Rotate1Click(TObject *Sender);
    void __fastcall Scale1Click(TObject *Sender);
    void __fastcall Mirror1Click(TObject *Sender);
    void __fastcall Explode1Click(TObject *Sender);
    void __fastcall Group1Click(TObject *Sender);
    void __fastcall Erase1Click(TObject *Sender);
    void __fastcall ZoomAll1Click(TObject *Sender);
    void __fastcall ZoomWindow1Click(TObject *Sender);
    void __fastcall ZoomPage2Click(TObject *Sender);
    void __fastcall ZoomIn1Click(TObject *Sender);
    void __fastcall ZoomOut1Click(TObject *Sender);
    void __fastcall PageFirst1Click(TObject *Sender);
    void __fastcall PageLasttEnd1Click(TObject *Sender);
    void __fastcall PageNext1Click(TObject *Sender);
    void __fastcall PagePrevious1Click(TObject *Sender);
    void __fastcall SelectPage1Click(TObject *Sender);
    void __fastcall SavecurrentView1Click(TObject *Sender);
    void __fastcall ViewsList1Click(TObject *Sender);
    void __fastcall Page1Click(TObject *Sender);
    void __fastcall Layer1Click(TObject *Sender);
    void __fastcall Linetype1Click(TObject *Sender);
    void __fastcall TextStyle1Click(TObject *Sender);
    void __fastcall PointStyle1Click(TObject *Sender);
    void __fastcall HatchStyle1Click(TObject *Sender);
    void __fastcall Blocks1Click(TObject *Sender);
    void __fastcall DimensionStyle1Click(TObject *Sender);
    void __fastcall Grid1Click(TObject *Sender);
    void __fastcall ObjectSnap1Click(TObject *Sender);
    void __fastcall AngleSnap1Click(TObject *Sender);
    void __fastcall Units1Click(TObject *Sender);
    void __fastcall Private1Click(TObject *Sender);
    void __fastcall Preferences1Click(TObject *Sender);
    void __fastcall Point1Click(TObject *Sender);
    void __fastcall Line1Click(TObject *Sender);
    void __fastcall Polyline1Click(TObject *Sender);
    void __fastcall Spline1Click(TObject *Sender);
    void __fastcall centerradius1Click(TObject *Sender);
    void __fastcall CenterDiameter1Click(TObject *Sender);
    void __fastcall N2Points1Click(TObject *Sender);
    void __fastcall N3point1Click(TObject *Sender);
    void __fastcall ArcCSEClick(TObject *Sender);
    void __fastcall ArcSEMClick(TObject *Sender);
    void __fastcall ArcSMEClick(TObject *Sender);
    void __fastcall Ellipse1Click(TObject *Sender);
    void __fastcall Rectangle1Click(TObject *Sender);
    void __fastcall Horizontal1Click(TObject *Sender);
    void __fastcall Vertical1Click(TObject *Sender);
    void __fastcall Parallel1Click(TObject *Sender);
    void __fastcall Angular1Click(TObject *Sender);
    void __fastcall Radius1Click(TObject *Sender);
    void __fastcall Diameter1Click(TObject *Sender);
    void __fastcall Ordinate1Click(TObject *Sender);
    void __fastcall Hatch1Click(TObject *Sender);
    void __fastcall Text1Click(TObject *Sender);
    void __fastcall Symbol1Click(TObject *Sender);
    void __fastcall InsertBlock1Click(TObject *Sender);
    void __fastcall InsertImage1Click(TObject *Sender);
    void __fastcall DistanceArea1Click(TObject *Sender);
    void __fastcall PrintRectangles1Click(TObject *Sender);
    void __fastcall Statistics1Click(TObject *Sender);
    
    void __fastcall About1Click(TObject *Sender);
private:	// User declarations
public:		// User declarations
    __fastcall TForm1(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TForm1 *Form1;
//---------------------------------------------------------------------------
#endif
