#ifndef __RealMetaH
#define __RealMetaH
#include <vcl\graphics.hpp>
#include "wingdi.h"



#include <pshpack2.h>
typedef struct
{ DWORD		dwKey;
  WORD		hmf;
  SMALL_RECT	bbox;
  WORD		wInch;
  DWORD		dwReserved;
  WORD		wCheckSum;
} APMHEADER, *PAPMHEADER;
#include <poppack.h>

typedef struct tagPOINT16 {short int x; short int y;} POINT16;
typedef struct tagTRectD {double Left; double Top; double Right; double Bottom;} TRectD;
class PACKAGE TRealMetafile;

typedef enum {rmsEmpty,rmsNormal,rmsEnum} TRealMetafileState;

typedef enum {enumKeep, enumDiscard, enumAbort} TEnumAction;
// This definition was absent from the wingdi.h header file, for some reason
//AliSoft typedef tagEMRSELECTCOLORSPACE EMRSETCOLORSPACE,*PEMRSETCOLORSPACE;
//typedef struct tagEMRSELECTCOLORSPACE /*EMRSETCOLORSPACE,*PEMRSETCOLORSPACE;
//typedef tagEMRSELECTCOLORSPACE EMRSETCOLORSPACE,*PEMRSETCOLORSPACE;

typedef void __fastcall (__closure *TEmrEvent)(TRealMetafile *Sender, const ENHMETARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrHeaderEvent)(TRealMetafile *Sender, const ENHMETAHEADER *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyBezierEvent)(TRealMetafile *Sender,const EMRPOLYBEZIER *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolygonEvent)(TRealMetafile *Sender, const EMRPOLYGON *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyLineEvent)(TRealMetafile *Sender, const EMRPOLYLINE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyBezierToEvent)(TRealMetafile *Sender, const EMRPOLYBEZIERTO *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyLineToEvent)(TRealMetafile *Sender, const EMRPOLYLINETO *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyPolyLineEvent)(TRealMetafile *Sender, const EMRPOLYPOLYLINE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyPolygonEvent)(TRealMetafile *Sender, const EMRPOLYPOLYGON *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetWindowExtExEvent)(TRealMetafile *Sender, const EMRSETWINDOWEXTEX *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetWindowOrgExEvent)(TRealMetafile *Sender, const EMRSETWINDOWORGEX *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetViewportExtExEvent)(TRealMetafile *Sender, const EMRSETVIEWPORTEXTEX *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetViewportOrgExEvent)(TRealMetafile *Sender, const EMRSETVIEWPORTORGEX *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetBrushorgExEvent)(TRealMetafile *Sender, const EMRSETBRUSHORGEX *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrEofEvent)(TRealMetafile *Sender, const EMREOF *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetPixelvEvent)(TRealMetafile *Sender, const EMRSETPIXELV *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetMapperFlagsEvent)(TRealMetafile *Sender, const EMRSETMAPPERFLAGS *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetMapModeEvent)(TRealMetafile *Sender, const EMRSETMAPMODE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetBkModeEvent)(TRealMetafile *Sender, const EMRSETBKMODE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetPolyFillModeEvent)(TRealMetafile *Sender, const EMRSETPOLYFILLMODE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetRop2Event)(TRealMetafile *Sender, const EMRSETROP2 *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetStretchBltModeEvent)(TRealMetafile *Sender, const EMRSETSTRETCHBLTMODE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetTextAlignEvent)(TRealMetafile *Sender, const EMRSETTEXTALIGN *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetColorAdjustmentEvent)(TRealMetafile *Sender, const EMRSETCOLORADJUSTMENT *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetTextColorEvent)(TRealMetafile *Sender, const EMRSETTEXTCOLOR *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetBkColorEvent)(TRealMetafile *Sender, const EMRSETBKCOLOR *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrOffsetClipRgnEvent)(TRealMetafile *Sender, const EMROFFSETCLIPRGN *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrMoveToExEvent)(TRealMetafile *Sender, const EMRMOVETOEX *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetMetaRgnEvent)(TRealMetafile *Sender, const EMRSETMETARGN *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrExcludeClipRectEvent)(TRealMetafile *Sender, const EMREXCLUDECLIPRECT *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrIntersectClipRectEvent)(TRealMetafile *Sender, const EMRINTERSECTCLIPRECT *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrScaleViewportExtExEvent)(TRealMetafile *Sender, const EMRSCALEVIEWPORTEXTEX *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrScaleWindowExtExEvent)(TRealMetafile *Sender, const EMRSCALEWINDOWEXTEX *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSaveDCEvent)(TRealMetafile *Sender, const EMRSAVEDC *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrRestoreDCEvent)(TRealMetafile *Sender, const EMRRESTOREDC *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetWorldTransformEvent)(TRealMetafile *Sender, const EMRSETWORLDTRANSFORM *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrModifyWorldTransformEvent)(TRealMetafile *Sender, const EMRMODIFYWORLDTRANSFORM *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSelectObjectEvent)(TRealMetafile *Sender, const EMRSELECTOBJECT *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrCreatePenEvent)(TRealMetafile *Sender, const EMRCREATEPEN *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrCreateBrushIndirectEvent)(TRealMetafile *Sender, const EMRCREATEBRUSHINDIRECT *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrDeleteObjectEvent)(TRealMetafile *Sender, const EMRDELETEOBJECT *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrAngleArcEvent)(TRealMetafile *Sender, const EMRANGLEARC *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrEllipseEvent)(TRealMetafile *Sender, const EMRELLIPSE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrRectangleEvent)(TRealMetafile *Sender, const EMRRECTANGLE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrRoundRectEvent)(TRealMetafile *Sender, const EMRROUNDRECT *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrArcEvent)(TRealMetafile *Sender, const EMRARC *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrChordEvent)(TRealMetafile *Sender, const EMRCHORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPieEvent)(TRealMetafile *Sender, const EMRPIE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSelectPaletteEvent)(TRealMetafile *Sender, const EMRSELECTPALETTE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrCreatePaletteEvent)(TRealMetafile *Sender, const EMRCREATEPALETTE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetPaletteEntriesEvent)(TRealMetafile *Sender, const EMRSETPALETTEENTRIES *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrResizePaletteEvent)(TRealMetafile *Sender, const EMRRESIZEPALETTE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrRealizePaletteEvent)(TRealMetafile *Sender, const EMRREALIZEPALETTE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrExtFloodFillEvent)(TRealMetafile *Sender, const EMREXTFLOODFILL *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrLineToEvent)(TRealMetafile *Sender, const EMRLINETO *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrArcToEvent)(TRealMetafile *Sender, const EMRARCTO *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyDrawEvent)(TRealMetafile *Sender, const EMRPOLYDRAW *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetArcDirectionEvent)(TRealMetafile *Sender, const EMRSETARCDIRECTION *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetMiterLimitEvent)(TRealMetafile *Sender, const EMRSETMITERLIMIT *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrBeginPathEvent)(TRealMetafile *Sender, const EMRBEGINPATH *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrEndPathEvent)(TRealMetafile *Sender, const EMRENDPATH *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrCloseFigureEvent)(TRealMetafile *Sender, const EMRCLOSEFIGURE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrFillPathEvent)(TRealMetafile *Sender, const EMRFILLPATH *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrStrokeAndFillpathEvent)(TRealMetafile *Sender, const EMRSTROKEANDFILLPATH *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrStrokePathEvent)(TRealMetafile *Sender, const EMRSTROKEPATH *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrFlattenPathEvent)(TRealMetafile *Sender, const EMRFLATTENPATH *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrWidenPathEvent)(TRealMetafile *Sender, const EMRWIDENPATH *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSelectClipPathEvent)(TRealMetafile *Sender, const EMRSELECTCLIPPATH *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrAbortPathEvent)(TRealMetafile *Sender, const EMRABORTPATH *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrGdiCommentEvent)(TRealMetafile *Sender, const EMRGDICOMMENT *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrFillRgnEvent)(TRealMetafile *Sender, const EMRFILLRGN *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrFrameRgnEvent)(TRealMetafile *Sender, const EMRFRAMERGN *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrInvertRgnEvent)(TRealMetafile *Sender, const EMRINVERTRGN *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPaintRgnEvent)(TRealMetafile *Sender, const EMRPAINTRGN *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrExtSelectClipRgnEvent)(TRealMetafile *Sender, const EMREXTSELECTCLIPRGN *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrBitBltEvent)(TRealMetafile *Sender, const EMRBITBLT *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrStretchBltEvent)(TRealMetafile *Sender, const EMRSTRETCHBLT *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrMaskBltEvent)(TRealMetafile *Sender, const EMRMASKBLT *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPlgBltEvent)(TRealMetafile *Sender, const EMRPLGBLT *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetDIBitsToDeviceEvent)(TRealMetafile *Sender, const EMRSETDIBITSTODEVICE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrStretchDIBitsEvent)(TRealMetafile *Sender, const EMRSTRETCHDIBITS *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrExtCreateFontIndirectWEvent)(TRealMetafile *Sender, const EMREXTCREATEFONTINDIRECTW *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrExtTextOutAEvent)(TRealMetafile *Sender, const EMREXTTEXTOUTA *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrExtTextOutWEvent)(TRealMetafile *Sender, const EMREXTTEXTOUTW *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyBezier16Event)(TRealMetafile *Sender, const EMRPOLYBEZIER16 *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolygon16Event)(TRealMetafile *Sender, const EMRPOLYGON16 *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyLine16Event)(TRealMetafile *Sender, const EMRPOLYLINE16 *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyBezierTo16Event)(TRealMetafile *Sender, const EMRPOLYBEZIERTO16 *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyLineTo16Event)(TRealMetafile *Sender, const EMRPOLYLINETO16 *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyPolyLine16Event)(TRealMetafile *Sender, const EMRPOLYPOLYLINE16 *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyPolygon16Event)(TRealMetafile *Sender, const EMRPOLYPOLYGON16 *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyDraw16Event)(TRealMetafile *Sender, const EMRPOLYDRAW16 *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrCreateMonoBrushEvent)(TRealMetafile *Sender, const EMRCREATEMONOBRUSH *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrCreateDIBPatternBrushPtEvent)(TRealMetafile *Sender, const EMRCREATEDIBPATTERNBRUSHPT *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrExtCreatePenEvent)(TRealMetafile *Sender, const EMREXTCREATEPEN *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyTextOutAEvent)(TRealMetafile *Sender, const EMRPOLYTEXTOUTA *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPolyTextOutWEvent)(TRealMetafile *Sender, const EMRPOLYTEXTOUTW *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetICMModeEvent)(TRealMetafile *Sender, const EMRSETICMMODE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrCreateColorSpaceEvent)(TRealMetafile *Sender, const EMRCREATECOLORSPACE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrSetColorSpaceEvent)(TRealMetafile *Sender, const EMRSETCOLORSPACE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrDeleteColorSpaceEvent)(TRealMetafile *Sender, const EMRDELETECOLORSPACE *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrGLSRecordEvent)(TRealMetafile *Sender, const EMRGLSRECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrGLSBoundedRecordEvent)(TRealMetafile *Sender, const EMRGLSBOUNDEDRECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TEmrPixelFormatEvent)(TRealMetafile *Sender, const EMRPIXELFORMAT *rec,TEnumAction &Action);


typedef void __fastcall (__closure *TWmrEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetBkColorEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetBkModeEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetMapModeEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetRop2Event)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetRelabsEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetPolyFillModeEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetStretchBltModeEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetTextCharExtraEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetTextColorEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetTextJustificationEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetWindowOrgEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetWindowExtEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetViewportOrgEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetViewportExtEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrOffSetWindowOrgEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrScaleWindowExtEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrOffSetViewportOrgEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrScaleViewportExtEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrLineToEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrMoveToEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrExcludeClipRectEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrIntersectClipRectEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrArcEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrEllipseEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrFloodFillEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrPieEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrRectangleEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrRoundRectEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrPatBltEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSaveDCEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetPixelEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrOffSetClipRgnEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrTextOutEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrBitBltEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrStretchBltEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrPolygonEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrPolyLineEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrEscapeEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrResToReDCEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrFillRegionEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrFrameRegionEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrInvertRegionEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrPaintRegionEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSelectClipRegionEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSelectObjectEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetTextAlignEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrChordEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetMapperFlagsEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrExtTextOutEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetDIBToDevEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSelectPaletteEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrRealizePaletteEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrAnimatePaletteEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrSetPalEntriesEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrPolyPolygonEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrResizePaletteEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrDIBBitBltEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrDIBStretchBltEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrDIBCreatePatternBrushEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrStretchDIBEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrExtFloodFillEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrDeleteObjectEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrCreatePaletteEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrCreatePatternBrushEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrCreatePenIndirectEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrCreateFontIndirectEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrCreateBrushIndirectEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrCreateRegionEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);
typedef void __fastcall (__closure *TWmrEvent)(TRealMetafile *Sender, const METARECORD *rec,TEnumAction &Action);



typedef int __fastcall (__closure *TMetafileCallback)(HDC hdc,HANDLETABLE *HTable, METARECORD *rec,int nObj);
typedef int __fastcall (__closure *TEnhMetafileCallback)(HDC hdc,HANDLETABLE *HTable, const ENHMETARECORD *rec,int nObj);


class PACKAGE TRealMetafile : public TComponent
{
public:
  __fastcall virtual TRealMetafile(TComponent *Owner);
  __fastcall virtual ~TRealMetafile();
  void __fastcall Assign(TPersistent *Source);
  //
  __property HENHMETAFILE EnhMetafile = {read=GetEnhMetafile};
  __property HMETAFILE WinMetafile = {read=GetWinMetafile};
  __property int MMWidth = {read=GetMMWidth,write=SetMMWidth};
  __property int MMHeight = {read=GetMMHeight,write=SetMMHeight};
  __property bool Enhanced = {read=GetEnhanced,write=SetEnhanced};
  __property TRealMetafileState State = {read=FState};
  __property AnsiString Status = {read=GetStatus};
  //
  bool __fastcall LoadFromFile(AnsiString fn);
  bool __fastcall LoadFromStream(TStream *Stream);
  bool __fastcall LoadFromClipboard();
  bool __fastcall SaveToFile(AnsiString fn);
  bool __fastcall SaveToStream(TStream *Stream);
  bool __fastcall SaveToClipboard();
  void __fastcall Clear();
  //
  void __fastcall Enum();
  void __fastcall EnumToMetafile(TRealMetafile *mdest,bool trim);
  void __fastcall EnumIntoCanvas(TCanvas *cdest,int x,int y);
  void __fastcall Draw(TCanvas *cdest,int x,int y);
  void __fastcall StretchDraw(TCanvas *cdest,TRect &rdst);
  // these are things you can access when enumming to metafile or canvas
  __property AnsiString RecordString = {read=GetRecordString};
  __property HDC hDC = {read=FhDC};
  __property TCanvas* Canvas = {read=GetCanvas};
  __property THandle ObjectHandle[int i] = {read=GetObjectHandle};
  __property HANDLETABLE *HandleTable = {read=FHandleTable};
  __property ENHMETARECORD *EnhRec = {read=GetEnhRec};
  __property METARECORD *WinRec = {read=GetWinRec};
  __property int NumHandles = {read=FNumHandles};
  __property LOGFONT CurrentFont = {read=GetCurrentFont};
  __property LOGPEN CurrentPen = {read=GetCurrentPen};
  __property LOGBRUSH CurrentBrush = {read=GetCurrentBrush};
  void __fastcall PlayCurrentRecord(); // unless you do emrDiscard, this isn't normally needed
  // these are things only relevant after enumming to a canvas
  __property TRect BoundsLog = {read=FBoundsLog};
  __property TRect BoundsDev = {read=FBoundsDev};
  //
protected:
  // following are for the actual image itself
  TRealMetafileState FState;
  HENHMETAFILE FEmf; HENHMETAFILE __fastcall GetEnhMetafile(); void __fastcall SetEnhMetafile(HENHMETAFILE emf);
  HMETAFILE FWmf;    HMETAFILE __fastcall GetWinMetafile(); void __fastcall SetWinMetafile(HMETAFILE wmf);
  int FMMWidth;      int __fastcall GetMMWidth(); void __fastcall SetMMWidth(int w);
  int FMMHeight;     int __fastcall GetMMHeight(); void __fastcall SetMMHeight(int h);
  bool FEnhanced;    bool __fastcall GetEnhanced(); void __fastcall SetEnhanced(bool b);
  AnsiString __fastcall GetStatus();
  // following are for enumming
  int __fastcall EnumMetafileProc(HDC hdc,HANDLETABLE *HTable, METARECORD *rec,int nObj);
  int __fastcall EnumEnhMetafileProc(HDC hdc,HANDLETABLE *HTable, const ENHMETARECORD *rec,int nObj);
  ENHMETARECORD *FEnhRec; METARECORD *FWinRec;
  LOGFONT FEnumCurrentFont; LOGFONT __fastcall GetCurrentFont();
  LOGPEN FEnumCurrentPen; LOGPEN __fastcall GetCurrentPen();
  LOGBRUSH FEnumCurrentBrush; LOGBRUSH __fastcall GetCurrentBrush();
  void __fastcall InitializeEnum(); void __fastcall EndEnum(); bool OwnCanvas;
  void __fastcall InternalSelectObject(int nObj);
  AnsiString __fastcall GetRecordString();
  ENHMETARECORD* __fastcall GetEnhRec(); METARECORD* __fastcall GetWinRec();
  HDC FhDC; TCanvas *FCanvas; TCanvas* __fastcall GetCanvas();
  HANDLETABLE *FHandleTable;  int FNumHandles; THandle __fastcall GetObjectHandle(int i);
  TRect FBoundsDev, FBoundsLog;
  //
__published:
  __property TEmrEvent OnEmr = {read=FEmr,write=FEmr,default=NULL};
  __property TEmrHeaderEvent OnEmrHeader = {read=FEmrHeader,write=FEmrHeader,default=NULL};
  __property TEmrPolyBezierEvent OnEmrPolyBezier = {read=FEmrPolyBezier,write=FEmrPolyBezier,default=NULL};
  __property TEmrPolygonEvent OnEmrPolygon = {read=FEmrPolygon,write=FEmrPolygon,default=NULL};
  __property TEmrPolyLineEvent OnEmrPolyLine = {read=FEmrPolyLine,write=FEmrPolyLine,default=NULL};
  __property TEmrPolyBezierToEvent OnEmrPolyBezierTo = {read=FEmrPolyBezierTo,write=FEmrPolyBezierTo,default=NULL};
  __property TEmrPolyLineToEvent OnEmrPolyLineTo = {read=FEmrPolyLineTo,write=FEmrPolyLineTo,default=NULL};
  __property TEmrPolyPolyLineEvent OnEmrPolyPolyLine = {read=FEmrPolyPolyLine,write=FEmrPolyPolyLine,default=NULL};
  __property TEmrPolyPolygonEvent OnEmrPolyPolygon = {read=FEmrPolyPolygon,write=FEmrPolyPolygon,default=NULL};
  __property TEmrSetWindowExtExEvent OnEmrSetWindowExtEx = {read=FEmrSetWindowExtEx,write=FEmrSetWindowExtEx,default=NULL};
  __property TEmrSetWindowOrgExEvent OnEmrSetWindowOrgEx = {read=FEmrSetWindowOrgEx,write=FEmrSetWindowOrgEx,default=NULL};
  __property TEmrSetViewportExtExEvent OnEmrSetViewportExtEx = {read=FEmrSetViewportExtEx,write=FEmrSetViewportExtEx,default=NULL};
  __property TEmrSetViewportOrgExEvent OnEmrSetViewportOrgEx = {read=FEmrSetViewportOrgEx,write=FEmrSetViewportOrgEx,default=NULL};
  __property TEmrSetBrushorgExEvent OnEmrSetBrushorgEx = {read=FEmrSetBrushorgEx,write=FEmrSetBrushorgEx,default=NULL};
  __property TEmrEofEvent OnEmrEof = {read=FEmrEof,write=FEmrEof,default=NULL};
  __property TEmrSetPixelvEvent OnEmrSetPixelv = {read=FEmrSetPixelv,write=FEmrSetPixelv,default=NULL};
  __property TEmrSetMapperFlagsEvent OnEmrSetMapperFlags = {read=FEmrSetMapperFlags,write=FEmrSetMapperFlags,default=NULL};
  __property TEmrSetMapModeEvent OnEmrSetMapMode = {read=FEmrSetMapMode,write=FEmrSetMapMode,default=NULL};
  __property TEmrSetBkModeEvent OnEmrSetBkMode = {read=FEmrSetBkMode,write=FEmrSetBkMode,default=NULL};
  __property TEmrSetPolyFillModeEvent OnEmrSetPolyFillMode = {read=FEmrSetPolyFillMode,write=FEmrSetPolyFillMode,default=NULL};
  __property TEmrSetRop2Event OnEmrSetRop2 = {read=FEmrSetRop2,write=FEmrSetRop2,default=NULL};
  __property TEmrSetStretchBltModeEvent OnEmrSetStretchBltMode = {read=FEmrSetStretchBltMode,write=FEmrSetStretchBltMode,default=NULL};
  __property TEmrSetTextAlignEvent OnEmrSetTextAlign = {read=FEmrSetTextAlign,write=FEmrSetTextAlign,default=NULL};
  __property TEmrSetColorAdjustmentEvent OnEmrSetColorAdjustment = {read=FEmrSetColorAdjustment,write=FEmrSetColorAdjustment,default=NULL};
  __property TEmrSetTextColorEvent OnEmrSetTextColor = {read=FEmrSetTextColor,write=FEmrSetTextColor,default=NULL};
  __property TEmrSetBkColorEvent OnEmrSetBkColor = {read=FEmrSetBkColor,write=FEmrSetBkColor,default=NULL};
  __property TEmrOffsetClipRgnEvent OnEmrOffsetClipRgn = {read=FEmrOffsetClipRgn,write=FEmrOffsetClipRgn,default=NULL};
  __property TEmrMoveToExEvent OnEmrMoveToEx = {read=FEmrMoveToEx,write=FEmrMoveToEx,default=NULL};
  __property TEmrSetMetaRgnEvent OnEmrSetMetaRgn = {read=FEmrSetMetaRgn,write=FEmrSetMetaRgn,default=NULL};
  __property TEmrExcludeClipRectEvent OnEmrExcludeClipRect = {read=FEmrExcludeClipRect,write=FEmrExcludeClipRect,default=NULL};
  __property TEmrIntersectClipRectEvent OnEmrIntersectClipRect = {read=FEmrIntersectClipRect,write=FEmrIntersectClipRect,default=NULL};
  __property TEmrScaleViewportExtExEvent OnEmrScaleViewportExtEx = {read=FEmrScaleViewportExtEx,write=FEmrScaleViewportExtEx,default=NULL};
  __property TEmrScaleWindowExtExEvent OnEmrScaleWindowExtEx = {read=FEmrScaleWindowExtEx,write=FEmrScaleWindowExtEx,default=NULL};
  __property TEmrSaveDCEvent OnEmrSaveDC = {read=FEmrSaveDC,write=FEmrSaveDC,default=NULL};
  __property TEmrRestoreDCEvent OnEmrRestoreDC = {read=FEmrRestoreDC,write=FEmrRestoreDC,default=NULL};
  __property TEmrSetWorldTransformEvent OnEmrSetWorldTransform = {read=FEmrSetWorldTransform,write=FEmrSetWorldTransform,default=NULL};
  __property TEmrModifyWorldTransformEvent OnEmrModifyWorldTransform = {read=FEmrModifyWorldTransform,write=FEmrModifyWorldTransform,default=NULL};
  __property TEmrSelectObjectEvent OnEmrSelectObject = {read=FEmrSelectObject,write=FEmrSelectObject,default=NULL};
  __property TEmrCreatePenEvent OnEmrCreatePen = {read=FEmrCreatePen,write=FEmrCreatePen,default=NULL};
  __property TEmrCreateBrushIndirectEvent OnEmrCreateBrushIndirect = {read=FEmrCreateBrushIndirect,write=FEmrCreateBrushIndirect,default=NULL};
  __property TEmrDeleteObjectEvent OnEmrDeleteObject = {read=FEmrDeleteObject,write=FEmrDeleteObject,default=NULL};
  __property TEmrAngleArcEvent OnEmrAngleArc = {read=FEmrAngleArc,write=FEmrAngleArc,default=NULL};
  __property TEmrEllipseEvent OnEmrEllipse = {read=FEmrEllipse,write=FEmrEllipse,default=NULL};
  __property TEmrRectangleEvent OnEmrRectangle = {read=FEmrRectangle,write=FEmrRectangle,default=NULL};
  __property TEmrRoundRectEvent OnEmrRoundRect = {read=FEmrRoundRect,write=FEmrRoundRect,default=NULL};
  __property TEmrArcEvent OnEmrArc = {read=FEmrArc,write=FEmrArc,default=NULL};
  __property TEmrChordEvent OnEmrChord = {read=FEmrChord,write=FEmrChord,default=NULL};
  __property TEmrPieEvent OnEmrPie = {read=FEmrPie,write=FEmrPie,default=NULL};
  __property TEmrSelectPaletteEvent OnEmrSelectPalette = {read=FEmrSelectPalette,write=FEmrSelectPalette,default=NULL};
  __property TEmrCreatePaletteEvent OnEmrCreatePalette = {read=FEmrCreatePalette,write=FEmrCreatePalette,default=NULL};
  __property TEmrSetPaletteEntriesEvent OnEmrSetPaletteEntries = {read=FEmrSetPaletteEntries,write=FEmrSetPaletteEntries,default=NULL};
  __property TEmrResizePaletteEvent OnEmrResizePalette = {read=FEmrResizePalette,write=FEmrResizePalette,default=NULL};
  __property TEmrRealizePaletteEvent OnEmrRealizePalette = {read=FEmrRealizePalette,write=FEmrRealizePalette,default=NULL};
  __property TEmrExtFloodFillEvent OnEmrExtFloodFill = {read=FEmrExtFloodFill,write=FEmrExtFloodFill,default=NULL};
  __property TEmrLineToEvent OnEmrLineTo = {read=FEmrLineTo,write=FEmrLineTo,default=NULL};
  __property TEmrArcToEvent OnEmrArcTo = {read=FEmrArcTo,write=FEmrArcTo,default=NULL};
  __property TEmrPolyDrawEvent OnEmrPolyDraw = {read=FEmrPolyDraw,write=FEmrPolyDraw,default=NULL};
  __property TEmrSetArcDirectionEvent OnEmrSetArcDirection = {read=FEmrSetArcDirection,write=FEmrSetArcDirection,default=NULL};
  __property TEmrSetMiterLimitEvent OnEmrSetMiterLimit = {read=FEmrSetMiterLimit,write=FEmrSetMiterLimit,default=NULL};
  __property TEmrBeginPathEvent OnEmrBeginPath = {read=FEmrBeginPath,write=FEmrBeginPath,default=NULL};
  __property TEmrEndPathEvent OnEmrEndPath = {read=FEmrEndPath,write=FEmrEndPath,default=NULL};
  __property TEmrCloseFigureEvent OnEmrCloseFigure = {read=FEmrCloseFigure,write=FEmrCloseFigure,default=NULL};
  __property TEmrFillPathEvent OnEmrFillPath = {read=FEmrFillPath,write=FEmrFillPath,default=NULL};
  __property TEmrStrokeAndFillpathEvent OnEmrStrokeAndFillpath = {read=FEmrStrokeAndFillpath,write=FEmrStrokeAndFillpath,default=NULL};
  __property TEmrStrokePathEvent OnEmrStrokePath = {read=FEmrStrokePath,write=FEmrStrokePath,default=NULL};
  __property TEmrFlattenPathEvent OnEmrFlattenPath = {read=FEmrFlattenPath,write=FEmrFlattenPath,default=NULL};
  __property TEmrWidenPathEvent OnEmrWidenPath = {read=FEmrWidenPath,write=FEmrWidenPath,default=NULL};
  __property TEmrSelectClipPathEvent OnEmrSelectClipPath = {read=FEmrSelectClipPath,write=FEmrSelectClipPath,default=NULL};
  __property TEmrAbortPathEvent OnEmrAbortPath = {read=FEmrAbortPath,write=FEmrAbortPath,default=NULL};
  __property TEmrGdiCommentEvent OnEmrGdiComment = {read=FEmrGdiComment,write=FEmrGdiComment,default=NULL};
  __property TEmrFillRgnEvent OnEmrFillRgn = {read=FEmrFillRgn,write=FEmrFillRgn,default=NULL};
  __property TEmrFrameRgnEvent OnEmrFrameRgn = {read=FEmrFrameRgn,write=FEmrFrameRgn,default=NULL};
  __property TEmrInvertRgnEvent OnEmrInvertRgn = {read=FEmrInvertRgn,write=FEmrInvertRgn,default=NULL};
  __property TEmrPaintRgnEvent OnEmrPaintRgn = {read=FEmrPaintRgn,write=FEmrPaintRgn,default=NULL};
  __property TEmrExtSelectClipRgnEvent OnEmrExtSelectClipRgn = {read=FEmrExtSelectClipRgn,write=FEmrExtSelectClipRgn,default=NULL};
  __property TEmrBitBltEvent OnEmrBitBlt = {read=FEmrBitBlt,write=FEmrBitBlt,default=NULL};
  __property TEmrStretchBltEvent OnEmrStretchBlt = {read=FEmrStretchBlt,write=FEmrStretchBlt,default=NULL};
  __property TEmrMaskBltEvent OnEmrMaskBlt = {read=FEmrMaskBlt,write=FEmrMaskBlt,default=NULL};
  __property TEmrPlgBltEvent OnEmrPlgBlt = {read=FEmrPlgBlt,write=FEmrPlgBlt,default=NULL};
  __property TEmrSetDIBitsToDeviceEvent OnEmrSetDIBitsToDevice = {read=FEmrSetDIBitsToDevice,write=FEmrSetDIBitsToDevice,default=NULL};
  __property TEmrStretchDIBitsEvent OnEmrStretchDIBits = {read=FEmrStretchDIBits,write=FEmrStretchDIBits,default=NULL};
  __property TEmrExtCreateFontIndirectWEvent OnEmrExtCreateFontIndirectW = {read=FEmrExtCreateFontIndirectW,write=FEmrExtCreateFontIndirectW,default=NULL};
  __property TEmrExtTextOutAEvent OnEmrExtTextOutA = {read=FEmrExtTextOutA,write=FEmrExtTextOutA,default=NULL};
  __property TEmrExtTextOutWEvent OnEmrExtTextOutW = {read=FEmrExtTextOutW,write=FEmrExtTextOutW,default=NULL};
  __property TEmrPolyBezier16Event OnEmrPolyBezier16 = {read=FEmrPolyBezier16,write=FEmrPolyBezier16,default=NULL};
  __property TEmrPolygon16Event OnEmrPolygon16 = {read=FEmrPolygon16,write=FEmrPolygon16,default=NULL};
  __property TEmrPolyLine16Event OnEmrPolyLine16 = {read=FEmrPolyLine16,write=FEmrPolyLine16,default=NULL};
  __property TEmrPolyBezierTo16Event OnEmrPolyBezierTo16 = {read=FEmrPolyBezierTo16,write=FEmrPolyBezierTo16,default=NULL};
  __property TEmrPolyLineTo16Event OnEmrPolyLineTo16 = {read=FEmrPolyLineTo16,write=FEmrPolyLineTo16,default=NULL};
  __property TEmrPolyPolyLine16Event OnEmrPolyPolyLine16 = {read=FEmrPolyPolyLine16,write=FEmrPolyPolyLine16,default=NULL};
  __property TEmrPolyPolygon16Event OnEmrPolyPolygon16 = {read=FEmrPolyPolygon16,write=FEmrPolyPolygon16,default=NULL};
  __property TEmrPolyDraw16Event OnEmrPolyDraw16 = {read=FEmrPolyDraw16,write=FEmrPolyDraw16,default=NULL};
  __property TEmrCreateMonoBrushEvent OnEmrCreateMonoBrush = {read=FEmrCreateMonoBrush,write=FEmrCreateMonoBrush,default=NULL};
  __property TEmrCreateDIBPatternBrushPtEvent OnEmrCreateDIBPatternBrushPt = {read=FEmrCreateDIBPatternBrushPt,write=FEmrCreateDIBPatternBrushPt,default=NULL};
  __property TEmrExtCreatePenEvent OnEmrExtCreatePen = {read=FEmrExtCreatePen,write=FEmrExtCreatePen,default=NULL};
  __property TEmrPolyTextOutAEvent OnEmrPolyTextOutA = {read=FEmrPolyTextOutA,write=FEmrPolyTextOutA,default=NULL};
  __property TEmrPolyTextOutWEvent OnEmrPolyTextOutW = {read=FEmrPolyTextOutW,write=FEmrPolyTextOutW,default=NULL};
  __property TEmrSetICMModeEvent OnEmrSetICMMode = {read=FEmrSetICMMode,write=FEmrSetICMMode,default=NULL};
  __property TEmrCreateColorSpaceEvent OnEmrCreateColorSpace = {read=FEmrCreateColorSpace,write=FEmrCreateColorSpace,default=NULL};
  __property TEmrSetColorSpaceEvent OnEmrSetColorSpace = {read=FEmrSetColorSpace,write=FEmrSetColorSpace,default=NULL};
  __property TEmrDeleteColorSpaceEvent OnEmrDeleteColorSpace = {read=FEmrDeleteColorSpace,write=FEmrDeleteColorSpace,default=NULL};
  __property TEmrGLSRecordEvent OnEmrGLSRecord = {read=FEmrGLSRecord,write=FEmrGLSRecord,default=NULL};
  __property TEmrGLSBoundedRecordEvent OnEmrGLSBoundedRecord = {read=FEmrGLSBoundedRecord,write=FEmrGLSBoundedRecord,default=NULL};
  __property TEmrPixelFormatEvent OnEmrPixelFormat = {read=FEmrPixelFormat,write=FEmrPixelFormat,default=NULL};
  //
  __property TWmrEvent OnWmr = {read=FWmr,write=FWmr,default=NULL};
  __property TWmrSetBkColorEvent OnWmrSetBkColor = {read=FWmrSetBkColor,write=FWmrSetBkColor,default=NULL};
  __property TWmrSetBkModeEvent OnWmrSetBkMode = {read=FWmrSetBkMode,write=FWmrSetBkMode,default=NULL};
  __property TWmrSetMapModeEvent OnWmrSetMapMode = {read=FWmrSetMapMode,write=FWmrSetMapMode,default=NULL};
  __property TWmrSetRop2Event OnWmrSetRop2 = {read=FWmrSetRop2,write=FWmrSetRop2,default=NULL};
  __property TWmrSetRelabsEvent OnWmrSetRelabs = {read=FWmrSetRelabs,write=FWmrSetRelabs,default=NULL};
  __property TWmrSetPolyFillModeEvent OnWmrSetPolyFillMode = {read=FWmrSetPolyFillMode,write=FWmrSetPolyFillMode,default=NULL};
  __property TWmrSetStretchBltModeEvent OnWmrSetStretchBltMode = {read=FWmrSetStretchBltMode,write=FWmrSetStretchBltMode,default=NULL};
  __property TWmrSetTextCharExtraEvent OnWmrSetTextCharExtra = {read=FWmrSetTextCharExtra,write=FWmrSetTextCharExtra,default=NULL};
  __property TWmrSetTextColorEvent OnWmrSetTextColor = {read=FWmrSetTextColor,write=FWmrSetTextColor,default=NULL};
  __property TWmrSetTextJustificationEvent OnWmrSetTextJustification = {read=FWmrSetTextJustification,write=FWmrSetTextJustification,default=NULL};
  __property TWmrSetWindowOrgEvent OnWmrSetWindowOrg = {read=FWmrSetWindowOrg,write=FWmrSetWindowOrg,default=NULL};
  __property TWmrSetWindowExtEvent OnWmrSetWindowExt = {read=FWmrSetWindowExt,write=FWmrSetWindowExt,default=NULL};
  __property TWmrSetViewportOrgEvent OnWmrSetViewportOrg = {read=FWmrSetViewportOrg,write=FWmrSetViewportOrg,default=NULL};
  __property TWmrSetViewportExtEvent OnWmrSetViewportExt = {read=FWmrSetViewportExt,write=FWmrSetViewportExt,default=NULL};
  __property TWmrOffSetWindowOrgEvent OnWmrOffSetWindowOrg = {read=FWmrOffSetWindowOrg,write=FWmrOffSetWindowOrg,default=NULL};
  __property TWmrScaleWindowExtEvent OnWmrScaleWindowExt = {read=FWmrScaleWindowExt,write=FWmrScaleWindowExt,default=NULL};
  __property TWmrOffSetViewportOrgEvent OnWmrOffSetViewportOrg = {read=FWmrOffSetViewportOrg,write=FWmrOffSetViewportOrg,default=NULL};
  __property TWmrScaleViewportExtEvent OnWmrScaleViewportExt = {read=FWmrScaleViewportExt,write=FWmrScaleViewportExt,default=NULL};
  __property TWmrLineToEvent OnWmrLineTo = {read=FWmrLineTo,write=FWmrLineTo,default=NULL};
  __property TWmrMoveToEvent OnWmrMoveTo = {read=FWmrMoveTo,write=FWmrMoveTo,default=NULL};
  __property TWmrExcludeClipRectEvent OnWmrExcludeClipRect = {read=FWmrExcludeClipRect,write=FWmrExcludeClipRect,default=NULL};
  __property TWmrIntersectClipRectEvent OnWmrIntersectClipRect = {read=FWmrIntersectClipRect,write=FWmrIntersectClipRect,default=NULL};
  __property TWmrArcEvent OnWmrArc = {read=FWmrArc,write=FWmrArc,default=NULL};
  __property TWmrEllipseEvent OnWmrEllipse = {read=FWmrEllipse,write=FWmrEllipse,default=NULL};
  __property TWmrFloodFillEvent OnWmrFloodFill = {read=FWmrFloodFill,write=FWmrFloodFill,default=NULL};
  __property TWmrPieEvent OnWmrPie = {read=FWmrPie,write=FWmrPie,default=NULL};
  __property TWmrRectangleEvent OnWmrRectangle = {read=FWmrRectangle,write=FWmrRectangle,default=NULL};
  __property TWmrRoundRectEvent OnWmrRoundRect = {read=FWmrRoundRect,write=FWmrRoundRect,default=NULL};
  __property TWmrPatBltEvent OnWmrPatBlt = {read=FWmrPatBlt,write=FWmrPatBlt,default=NULL};
  __property TWmrSaveDCEvent OnWmrSaveDC = {read=FWmrSaveDC,write=FWmrSaveDC,default=NULL};
  __property TWmrSetPixelEvent OnWmrSetPixel = {read=FWmrSetPixel,write=FWmrSetPixel,default=NULL};
  __property TWmrOffSetClipRgnEvent OnWmrOffSetClipRgn = {read=FWmrOffSetClipRgn,write=FWmrOffSetClipRgn,default=NULL};
  __property TWmrTextOutEvent OnWmrTextOut = {read=FWmrTextOut,write=FWmrTextOut,default=NULL};
  __property TWmrBitBltEvent OnWmrBitBlt = {read=FWmrBitBlt,write=FWmrBitBlt,default=NULL};
  __property TWmrStretchBltEvent OnWmrStretchBlt = {read=FWmrStretchBlt,write=FWmrStretchBlt,default=NULL};
  __property TWmrPolygonEvent OnWmrPolygon = {read=FWmrPolygon,write=FWmrPolygon,default=NULL};
  __property TWmrPolyLineEvent OnWmrPolyLine = {read=FWmrPolyLine,write=FWmrPolyLine,default=NULL};
  __property TWmrEscapeEvent OnWmrEscape = {read=FWmrEscape,write=FWmrEscape,default=NULL};
  __property TWmrResToReDCEvent OnWmrResToReDC = {read=FWmrResToReDC,write=FWmrResToReDC,default=NULL};
  __property TWmrFillRegionEvent OnWmrFillRegion = {read=FWmrFillRegion,write=FWmrFillRegion,default=NULL};
  __property TWmrFrameRegionEvent OnWmrFrameRegion = {read=FWmrFrameRegion,write=FWmrFrameRegion,default=NULL};
  __property TWmrInvertRegionEvent OnWmrInvertRegion = {read=FWmrInvertRegion,write=FWmrInvertRegion,default=NULL};
  __property TWmrPaintRegionEvent OnWmrPaintRegion = {read=FWmrPaintRegion,write=FWmrPaintRegion,default=NULL};
  __property TWmrSelectClipRegionEvent OnWmrSelectClipRegion = {read=FWmrSelectClipRegion,write=FWmrSelectClipRegion,default=NULL};
  __property TWmrSelectObjectEvent OnWmrSelectObject = {read=FWmrSelectObject,write=FWmrSelectObject,default=NULL};
  __property TWmrSetTextAlignEvent OnWmrSetTextAlign = {read=FWmrSetTextAlign,write=FWmrSetTextAlign,default=NULL};
  __property TWmrChordEvent OnWmrChord = {read=FWmrChord,write=FWmrChord,default=NULL};
  __property TWmrSetMapperFlagsEvent OnWmrSetMapperFlags = {read=FWmrSetMapperFlags,write=FWmrSetMapperFlags,default=NULL};
  __property TWmrExtTextOutEvent OnWmrExtTextOut = {read=FWmrExtTextOut,write=FWmrExtTextOut,default=NULL};
  __property TWmrSetDIBToDevEvent OnWmrSetDIBToDev = {read=FWmrSetDIBToDev,write=FWmrSetDIBToDev,default=NULL};
  __property TWmrSelectPaletteEvent OnWmrSelectPalette = {read=FWmrSelectPalette,write=FWmrSelectPalette,default=NULL};
  __property TWmrRealizePaletteEvent OnWmrRealizePalette = {read=FWmrRealizePalette,write=FWmrRealizePalette,default=NULL};
  __property TWmrAnimatePaletteEvent OnWmrAnimatePalette = {read=FWmrAnimatePalette,write=FWmrAnimatePalette,default=NULL};
  __property TWmrSetPalEntriesEvent OnWmrSetPalEntries = {read=FWmrSetPalEntries,write=FWmrSetPalEntries,default=NULL};
  __property TWmrPolyPolygonEvent OnWmrPolyPolygon = {read=FWmrPolyPolygon,write=FWmrPolyPolygon,default=NULL};
  __property TWmrResizePaletteEvent OnWmrResizePalette = {read=FWmrResizePalette,write=FWmrResizePalette,default=NULL};
  __property TWmrDIBBitBltEvent OnWmrDIBBitBlt = {read=FWmrDIBBitBlt,write=FWmrDIBBitBlt,default=NULL};
  __property TWmrDIBStretchBltEvent OnWmrDIBStretchBlt = {read=FWmrDIBStretchBlt,write=FWmrDIBStretchBlt,default=NULL};
  __property TWmrDIBCreatePatternBrushEvent OnWmrDIBCreatePatternBrush = {read=FWmrDIBCreatePatternBrush,write=FWmrDIBCreatePatternBrush,default=NULL};
  __property TWmrStretchDIBEvent OnWmrStretchDIB = {read=FWmrStretchDIB,write=FWmrStretchDIB,default=NULL};
  __property TWmrExtFloodFillEvent OnWmrExtFloodFill = {read=FWmrExtFloodFill,write=FWmrExtFloodFill,default=NULL};
  __property TWmrDeleteObjectEvent OnWmrDeleteObject = {read=FWmrDeleteObject,write=FWmrDeleteObject,default=NULL};
  __property TWmrCreatePaletteEvent OnWmrCreatePalette = {read=FWmrCreatePalette,write=FWmrCreatePalette,default=NULL};
  __property TWmrCreatePatternBrushEvent OnWmrCreatePatternBrush = {read=FWmrCreatePatternBrush,write=FWmrCreatePatternBrush,default=NULL};
  __property TWmrCreatePenIndirectEvent OnWmrCreatePenIndirect = {read=FWmrCreatePenIndirect,write=FWmrCreatePenIndirect,default=NULL};
  __property TWmrCreateFontIndirectEvent OnWmrCreateFontIndirect = {read=FWmrCreateFontIndirect,write=FWmrCreateFontIndirect,default=NULL};
  __property TWmrCreateBrushIndirectEvent OnWmrCreateBrushIndirect = {read=FWmrCreateBrushIndirect,write=FWmrCreateBrushIndirect,default=NULL};
  __property TWmrCreateRegionEvent OnWmrCreateRegion = {read=FWmrCreateRegion,write=FWmrCreateRegion,default=NULL};
protected:
  TEmrEvent FEmr;
  TEmrHeaderEvent FEmrHeader;
  TEmrPolyBezierEvent FEmrPolyBezier;
  TEmrPolygonEvent FEmrPolygon;
  TEmrPolyLineEvent FEmrPolyLine;
  TEmrPolyBezierToEvent FEmrPolyBezierTo;
  TEmrPolyLineToEvent FEmrPolyLineTo;
  TEmrPolyPolyLineEvent FEmrPolyPolyLine;
  TEmrPolyPolygonEvent FEmrPolyPolygon;
  TEmrSetWindowExtExEvent FEmrSetWindowExtEx;
  TEmrSetWindowOrgExEvent FEmrSetWindowOrgEx;
  TEmrSetViewportExtExEvent FEmrSetViewportExtEx;
  TEmrSetViewportOrgExEvent FEmrSetViewportOrgEx;
  TEmrSetBrushorgExEvent FEmrSetBrushorgEx;
  TEmrEofEvent FEmrEof;
  TEmrSetPixelvEvent FEmrSetPixelv;
  TEmrSetMapperFlagsEvent FEmrSetMapperFlags;
  TEmrSetMapModeEvent FEmrSetMapMode;
  TEmrSetBkModeEvent FEmrSetBkMode;
  TEmrSetPolyFillModeEvent FEmrSetPolyFillMode;
  TEmrSetRop2Event FEmrSetRop2;
  TEmrSetStretchBltModeEvent FEmrSetStretchBltMode;
  TEmrSetTextAlignEvent FEmrSetTextAlign;
  TEmrSetColorAdjustmentEvent FEmrSetColorAdjustment;
  TEmrSetTextColorEvent FEmrSetTextColor;
  TEmrSetBkColorEvent FEmrSetBkColor;
  TEmrOffsetClipRgnEvent FEmrOffsetClipRgn;
  TEmrMoveToExEvent FEmrMoveToEx;
  TEmrSetMetaRgnEvent FEmrSetMetaRgn;
  TEmrExcludeClipRectEvent FEmrExcludeClipRect;
  TEmrIntersectClipRectEvent FEmrIntersectClipRect;
  TEmrScaleViewportExtExEvent FEmrScaleViewportExtEx;
  TEmrScaleWindowExtExEvent FEmrScaleWindowExtEx;
  TEmrSaveDCEvent FEmrSaveDC;
  TEmrRestoreDCEvent FEmrRestoreDC;
  TEmrSetWorldTransformEvent FEmrSetWorldTransform;
  TEmrModifyWorldTransformEvent FEmrModifyWorldTransform;
  TEmrSelectObjectEvent FEmrSelectObject;
  TEmrCreatePenEvent FEmrCreatePen;
  TEmrCreateBrushIndirectEvent FEmrCreateBrushIndirect;
  TEmrDeleteObjectEvent FEmrDeleteObject;
  TEmrAngleArcEvent FEmrAngleArc;
  TEmrEllipseEvent FEmrEllipse;
  TEmrRectangleEvent FEmrRectangle;
  TEmrRoundRectEvent FEmrRoundRect;
  TEmrArcEvent FEmrArc;
  TEmrChordEvent FEmrChord;
  TEmrPieEvent FEmrPie;
  TEmrSelectPaletteEvent FEmrSelectPalette;
  TEmrCreatePaletteEvent FEmrCreatePalette;
  TEmrSetPaletteEntriesEvent FEmrSetPaletteEntries;
  TEmrResizePaletteEvent FEmrResizePalette;
  TEmrRealizePaletteEvent FEmrRealizePalette;
  TEmrExtFloodFillEvent FEmrExtFloodFill;
  TEmrLineToEvent FEmrLineTo;
  TEmrArcToEvent FEmrArcTo;
  TEmrPolyDrawEvent FEmrPolyDraw;
  TEmrSetArcDirectionEvent FEmrSetArcDirection;
  TEmrSetMiterLimitEvent FEmrSetMiterLimit;
  TEmrBeginPathEvent FEmrBeginPath;
  TEmrEndPathEvent FEmrEndPath;
  TEmrCloseFigureEvent FEmrCloseFigure;
  TEmrFillPathEvent FEmrFillPath;
  TEmrStrokeAndFillpathEvent FEmrStrokeAndFillpath;
  TEmrStrokePathEvent FEmrStrokePath;
  TEmrFlattenPathEvent FEmrFlattenPath;
  TEmrWidenPathEvent FEmrWidenPath;
  TEmrSelectClipPathEvent FEmrSelectClipPath;
  TEmrAbortPathEvent FEmrAbortPath;
  TEmrGdiCommentEvent FEmrGdiComment;
  TEmrFillRgnEvent FEmrFillRgn;
  TEmrFrameRgnEvent FEmrFrameRgn;
  TEmrInvertRgnEvent FEmrInvertRgn;
  TEmrPaintRgnEvent FEmrPaintRgn;
  TEmrExtSelectClipRgnEvent FEmrExtSelectClipRgn;
  TEmrBitBltEvent FEmrBitBlt;
  TEmrStretchBltEvent FEmrStretchBlt;
  TEmrMaskBltEvent FEmrMaskBlt;
  TEmrPlgBltEvent FEmrPlgBlt;
  TEmrSetDIBitsToDeviceEvent FEmrSetDIBitsToDevice;
  TEmrStretchDIBitsEvent FEmrStretchDIBits;
  TEmrExtCreateFontIndirectWEvent FEmrExtCreateFontIndirectW;
  TEmrExtTextOutAEvent FEmrExtTextOutA;
  TEmrExtTextOutWEvent FEmrExtTextOutW;
  TEmrPolyBezier16Event FEmrPolyBezier16;
  TEmrPolygon16Event FEmrPolygon16;
  TEmrPolyLine16Event FEmrPolyLine16;
  TEmrPolyBezierTo16Event FEmrPolyBezierTo16;
  TEmrPolyLineTo16Event FEmrPolyLineTo16;
  TEmrPolyPolyLine16Event FEmrPolyPolyLine16;
  TEmrPolyPolygon16Event FEmrPolyPolygon16;
  TEmrPolyDraw16Event FEmrPolyDraw16;
  TEmrCreateMonoBrushEvent FEmrCreateMonoBrush;
  TEmrCreateDIBPatternBrushPtEvent FEmrCreateDIBPatternBrushPt;
  TEmrExtCreatePenEvent FEmrExtCreatePen;
  TEmrPolyTextOutAEvent FEmrPolyTextOutA;
  TEmrPolyTextOutWEvent FEmrPolyTextOutW;
  TEmrSetICMModeEvent FEmrSetICMMode;
  TEmrCreateColorSpaceEvent FEmrCreateColorSpace;
  TEmrSetColorSpaceEvent FEmrSetColorSpace;
  TEmrDeleteColorSpaceEvent FEmrDeleteColorSpace;
  TEmrGLSRecordEvent FEmrGLSRecord;
  TEmrGLSBoundedRecordEvent FEmrGLSBoundedRecord;
  TEmrPixelFormatEvent FEmrPixelFormat;
  //
  TWmrEvent FWmr;
  TWmrSetBkColorEvent FWmrSetBkColor;
  TWmrSetBkModeEvent FWmrSetBkMode;
  TWmrSetMapModeEvent FWmrSetMapMode;
  TWmrSetRop2Event FWmrSetRop2;
  TWmrSetRelabsEvent FWmrSetRelabs;
  TWmrSetPolyFillModeEvent FWmrSetPolyFillMode;
  TWmrSetStretchBltModeEvent FWmrSetStretchBltMode;
  TWmrSetTextCharExtraEvent FWmrSetTextCharExtra;
  TWmrSetTextColorEvent FWmrSetTextColor;
  TWmrSetTextJustificationEvent FWmrSetTextJustification;
  TWmrSetWindowOrgEvent FWmrSetWindowOrg;
  TWmrSetWindowExtEvent FWmrSetWindowExt;
  TWmrSetViewportOrgEvent FWmrSetViewportOrg;
  TWmrSetViewportExtEvent FWmrSetViewportExt;
  TWmrOffSetWindowOrgEvent FWmrOffSetWindowOrg;
  TWmrScaleWindowExtEvent FWmrScaleWindowExt;
  TWmrOffSetViewportOrgEvent FWmrOffSetViewportOrg;
  TWmrScaleViewportExtEvent FWmrScaleViewportExt;
  TWmrLineToEvent FWmrLineTo;
  TWmrMoveToEvent FWmrMoveTo;
  TWmrExcludeClipRectEvent FWmrExcludeClipRect;
  TWmrIntersectClipRectEvent FWmrIntersectClipRect;
  TWmrArcEvent FWmrArc;
  TWmrEllipseEvent FWmrEllipse;
  TWmrFloodFillEvent FWmrFloodFill;
  TWmrPieEvent FWmrPie;
  TWmrRectangleEvent FWmrRectangle;
  TWmrRoundRectEvent FWmrRoundRect;
  TWmrPatBltEvent FWmrPatBlt;
  TWmrSaveDCEvent FWmrSaveDC;
  TWmrSetPixelEvent FWmrSetPixel;
  TWmrOffSetClipRgnEvent FWmrOffSetClipRgn;
  TWmrTextOutEvent FWmrTextOut;
  TWmrBitBltEvent FWmrBitBlt;
  TWmrStretchBltEvent FWmrStretchBlt;
  TWmrPolygonEvent FWmrPolygon;
  TWmrPolyLineEvent FWmrPolyLine;
  TWmrEscapeEvent FWmrEscape;
  TWmrResToReDCEvent FWmrResToReDC;
  TWmrFillRegionEvent FWmrFillRegion;
  TWmrFrameRegionEvent FWmrFrameRegion;
  TWmrInvertRegionEvent FWmrInvertRegion;
  TWmrPaintRegionEvent FWmrPaintRegion;
  TWmrSelectClipRegionEvent FWmrSelectClipRegion;
  TWmrSelectObjectEvent FWmrSelectObject;
  TWmrSetTextAlignEvent FWmrSetTextAlign;
  TWmrChordEvent FWmrChord;
  TWmrSetMapperFlagsEvent FWmrSetMapperFlags;
  TWmrExtTextOutEvent FWmrExtTextOut;
  TWmrSetDIBToDevEvent FWmrSetDIBToDev;
  TWmrSelectPaletteEvent FWmrSelectPalette;
  TWmrRealizePaletteEvent FWmrRealizePalette;
  TWmrAnimatePaletteEvent FWmrAnimatePalette;
  TWmrSetPalEntriesEvent FWmrSetPalEntries;
  TWmrPolyPolygonEvent FWmrPolyPolygon;
  TWmrResizePaletteEvent FWmrResizePalette;
  TWmrDIBBitBltEvent FWmrDIBBitBlt;
  TWmrDIBStretchBltEvent FWmrDIBStretchBlt;
  TWmrDIBCreatePatternBrushEvent FWmrDIBCreatePatternBrush;
  TWmrStretchDIBEvent FWmrStretchDIB;
  TWmrExtFloodFillEvent FWmrExtFloodFill;
  TWmrDeleteObjectEvent FWmrDeleteObject;
  TWmrCreatePaletteEvent FWmrCreatePalette;
  TWmrCreatePatternBrushEvent FWmrCreatePatternBrush;
  TWmrCreatePenIndirectEvent FWmrCreatePenIndirect;
  TWmrCreateFontIndirectEvent FWmrCreateFontIndirect;
  TWmrCreateBrushIndirectEvent FWmrCreateBrushIndirect;
  TWmrCreateRegionEvent FWmrCreateRegion;
  //
  AnsiString __fastcall strRect(const RECTL &rc);
  AnsiString __fastcall strHex(const int d);
  AnsiString __fastcall strInt(const int d);
  AnsiString __fastcall strSize(const SIZE &sz);
  AnsiString __fastcall strPointL(const POINTL &pt);
  AnsiString __fastcall strPoint(const POINT &pt);
  AnsiString __fastcall strInt16(const int i);
  AnsiString __fastcall strPoint16(const POINT16 &pt);
  AnsiString __fastcall strBool(const BOOL b);
  AnsiString __fastcall strWChar(const WCHAR *t);
  AnsiString __fastcall strByteChar(const BYTE*t);
  AnsiString __fastcall strFloat(const double d);
  AnsiString __fastcall strMapMode(int m);
  AnsiString __fastcall strRop2(int m);
  AnsiString __fastcall strCharset(BYTE c);
  AnsiString __fastcall strOutPrecision(BYTE c);
  AnsiString __fastcall strClipPrecision(BYTE c);
  AnsiString __fastcall strQuality(BYTE c);
  AnsiString __fastcall strPitchAndFamily(BYTE c);
  AnsiString __fastcall strLogFont(const LOGFONTW &lf);
  AnsiString __fastcall strExtFont(const EXTLOGFONTW &elf);
  AnsiString __fastcall strTextAlign(const int a);
  AnsiString __fastcall strBkMode(const int m);
  AnsiString __fastcall strColorRef(const COLORREF &cr);
  AnsiString __fastcall strLogPenStyle(int s);
  AnsiString __fastcall strLogPen(const LOGPEN &lp);
  AnsiString __fastcall strLogBrushStyle(int s);
  AnsiString __fastcall strBrushHatch(LONG h);
  AnsiString __fastcall strLogBrush(const LOGBRUSH &lb);
  AnsiString __fastcall strPolyFillMode(const int m);
  AnsiString __fastcall strObject(const int i);
  AnsiString __fastcall strPolyLine16(int npt,POINT16 *pt);
  AnsiString __fastcall strEmrHeader(const ENHMETAHEADER *rec);
  AnsiString __fastcall strEmrGdiComment(const EMRGDICOMMENT *rec);
  AnsiString __fastcall strEmrSetMapMode(const EMRSETMAPMODE *rec);
  AnsiString __fastcall strEmrSetViewportExtEx(const EMRSETWINDOWEXTEX *rec);
  AnsiString __fastcall strEmrSetWindowExtEx(const EMRSETWINDOWEXTEX *rec);
  AnsiString __fastcall strEmrSetRop2(const EMRSETMAPMODE *rec);
  AnsiString __fastcall strEmrSetViewportOrgEx(const EMRSETWINDOWORGEX *rec);
  AnsiString __fastcall strEmrSetWindowOrgEx(const EMRSETWINDOWORGEX *rec);
  AnsiString __fastcall strEmrExtCreateFontIndirectW(const EMREXTCREATEFONTINDIRECTW *rec);
  AnsiString __fastcall strEmrSelectObject(const EMRSELECTOBJECT *rec);
  AnsiString __fastcall strEmrSetTextAlign(const EMRSETMAPMODE *rec);
  AnsiString __fastcall strEmrSetBkMode(const EMRSETMAPMODE *rec);
  AnsiString __fastcall strEmrSetTextColor(const EMRSETTEXTCOLOR *rec);
  AnsiString __fastcall strEmrExtTextOutW(const EMREXTTEXTOUTA *rec);
  AnsiString __fastcall strEmrCreatePen(const EMRCREATEPEN *rec);
  AnsiString __fastcall strEmrSetPolyFillMode(const EMRSETMAPMODE *rec);
  AnsiString __fastcall strEmrPolyPolygon16(const EMRPOLYPOLYLINE16 *rec);
  AnsiString __fastcall strEmrCreateBrushIndirect(const EMRCREATEBRUSHINDIRECT *rec);
  AnsiString __fastcall strEmrPolygon16(const EMRPOLYBEZIER16 *rec);
  AnsiString __fastcall strEmrDeleteObject(const EMRSELECTOBJECT *rec);
  AnsiString __fastcall strEmrPolyLine16(const EMRPOLYBEZIER16 *rec);
  AnsiString __fastcall strEmrSelectPalette(const EMRSELECTPALETTE *rec);
  AnsiString __fastcall strEmrExtSelectClipRgn(const EMREXTSELECTCLIPRGN *rec);
  AnsiString __fastcall strEmrEof(const EMREOF *rec);
  //
  AnsiString __fastcall strWmrSelectObject(const METARECORD *rec);

};



#endif